- run:
      name: Notify DatoCMS about the status of the job
      command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"failed\" } }" https://webhooks.datocms.com/00cd712a09/deploy-results'
      when: on_fail

    - run:
      name: Notify DatoCMS about the status of the job
      command: 'curl -X POST --data-binary "{\"payload\": { \"branch\": \"$CIRCLE_BRANCH\", \"status\": \"success\" } }" https://webhooks.datocms.com/00cd712a09/deploy-results'
      when: on_success
    